site_name: Proyecto Chimera
site_description: Backend Engineering Program — División Chimera

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  font:
    text: Inter
    code: JetBrains Mono
  favicon: assets/favicon.svg
  features:
    - navigation.instant
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
